"use client";
import { useState, useRef } from "react";
type Mode = "story" | "draft" | "phrase";
type Answer = Record<string,string>;
const phrases = ["Mas e as plantas?","Leão come carne.","Você vai ficar anêmica.","Eu respeito vegano, só não respeito quem impõe.","Você não vai comer nem um pedacinho?","Agora tudo tem que ser vegano?","Vocês se preocupam mais com bicho do que com gente."];
const styles = [["♥","Mais carinhosa"],["◎","Mais direta"],["✳","Com humor"],["✂","Mais curta"],["▣","Quero colocar um limite"]];
export default function Home(){
 const [mode,setMode]=useState<Mode>("story"),[text,setText]=useState(""),[phrase,setPhrase]=useState(phrases[0]),[answer,setAnswer]=useState<Answer|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[listening,setListening]=useState(false);
 const rec=useRef<any>(null);
 async function submit(refine?:string){
  if(mode!=="phrase"&&!text.trim()){setError("Conta um pouco do que aconteceu para eu poder ajudar.");return}
  setBusy(true);setError("");
  try{const r=await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode,text:mode==="phrase"?phrase:text,refine,previous:refine?answer:null})});if(!r.ok)throw Error();setAnswer(await r.json());setTimeout(()=>document.getElementById("resultado")?.scrollIntoView({behavior:"smooth"}),40)}
  catch{setError("Não consegui analisar agora. Tente novamente.")}finally{setBusy(false)}
 }
 function voice(){const Speech=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Speech){setError("Seu navegador não oferece ditado por voz.");return}if(listening){rec.current?.stop();return}const s=new Speech();rec.current=s;s.lang="pt-BR";s.continuous=true;s.onresult=(e:any)=>{const spoken=Array.from(e.results).slice(e.resultIndex).map((r:any)=>r[0].transcript).join(" ");setText(v=>v+(v?" ":"")+spoken)};s.onend=()=>setListening(false);s.onerror=()=>setError("A transcrição parou. Você pode continuar digitando.");s.start();setListening(true)}
 function choose(m:Mode){setMode(m);setAnswer(null);setError("")}
 return <main className="shell"><header className="topbar"><div className="logo">“<span>✳</span></div><strong>conversa<span className="dot">.</span></strong><small>um espaço para baixar a temperatura</small></header>
 <section className="hero"><div><p className="eyebrow">✳ CONVERSAS DIFÍCEIS, UM POUCO MAIS FÁCEIS</p><h1>Transformando<br/><em>Conflito</em> em Conversa<span className="dot">.</span></h1><h2>Um copiloto para conversas difíceis.</h2><p>Conte o que aconteceu. Eu te ajudo a entender o conflito e encontrar uma forma mais clara, empática e assertiva de conversar.</p></div><div className="hero-art" aria-hidden="true"><span>“</span><b>…</b><small>respira. dá pra conversar.</small></div></section>
 <section className="workspace"><div className="section-title"><div><p className="eyebrow">POR ONDE A GENTE COMEÇA?</p><h2>Escolha seu momento</h2></div><span>Sem julgamento. Sem texto engessado.</span></div>
 <div className="cards">
 <button className={mode==="story"?"active":""} onClick={()=>choose("story")}><i>💬</i><strong>Aconteceu uma treta</strong><span>Conte o que aconteceu do seu jeito. Pode reclamar mesmo.</span><small>01</small></button>
 <button className={mode==="draft"?"active":""} onClick={()=>choose("draft")}><i>👀</i><strong>Antes de eu mandar…</strong><span>Escreveu no calor do momento? Cola aqui antes de enviar.</span><small>02</small></button>
 <button className={mode==="phrase"?"active":""} onClick={()=>choose("phrase")}><i>🔥</i><strong>Me mandaram essa</strong><span>Aquela frase pronta apareceu? Vamos achar outra resposta.</span><small>03</small></button></div>
 <div className="input-panel"><div className="panel-meta"><span>{mode==="story"?"01 / ACONTECEU UMA TRETA":mode==="draft"?"02 / ANTES DE EU MANDAR":"03 / ME MANDARAM ESSA"}</span><span>◌ sem salvar sua conversa</span></div>
 {mode==="phrase"?<><h3>O que te disseram?</h3><div className="phrases">{phrases.map(p=><button key={p} className={p===phrase?"selected":""} onClick={()=>{setPhrase(p);setAnswer(null)}}>{p}</button>)}</div></>:<><h3>{mode==="story"?"Me conta o que aconteceu.":"Qual mensagem você pensou em enviar?"}</h3><p>{mode==="story"?"Escreva sem filtro. A gente organiza depois.":"Pode colar exatamente como está. A intenção é sua; eu ajudo com o tom."}</p><div className="field"><textarea maxLength={5000} value={text} onChange={e=>setText(e.target.value)} aria-label="Sua mensagem" placeholder={mode==="story"?"Meu pai falou que veganismo é frescura e que enquanto eu morar na casa dele vou ter que comer o que ele compra…":"Você nunca me escuta. Não adianta mais tentar conversar com você…"}></textarea><button onClick={voice} aria-label={listening?"Parar ditado":"Ditado por voz"}>{listening?"■":"🎙"}</button></div><small className="count">{text.length}/5000</small></>}
 {error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy} onClick={()=>submit()}>{busy?"Pensando com cuidado…":mode==="story"?"Me ajuda com essa conversa":mode==="draft"?"Revisar minha mensagem":"Pensar numa resposta"} <span>↗</span></button></div>
 {answer&&<section id="resultado" className="result" aria-live="polite"><p className="eyebrow">✳ UMA OUTRA FORMA DE OLHAR</p><h2>{answer.heading||"Vamos por partes."}</h2>{answer.note&&<p className="notice">{answer.note}</p>}
 <div className="insights">{(mode==="story"?[["O que está acontecendo aqui?",answer.reading],["O que pode estar por trás disso?",answer.behind],["Onde a conversa pode travar?",answer.friction],["Experimente esta abordagem",answer.approach]]:mode==="draft"?[["O que sua mensagem comunica",answer.tone],["Como ela pode ser recebida",answer.reception],["Onde pode nascer mais conflito",answer.risk]]:[["O impulso",answer.impulse],["O risco",answer.risk],["A virada",answer.turn]]).map(([title,body])=>body&&<article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div>
 <div className="reply"><small>{mode==="draft"?"UMA ALTERNATIVA":mode==="phrase"?"UMA RESPOSTA POSSÍVEL":"VOCÊ PODERIA DIZER"}</small><p>“{answer.reply}”</p></div><div className="refine"><h3>Essa resposta parece com você?</h3><div>{styles.map(([icon,label])=><button key={label} disabled={busy} onClick={()=>submit(label)}>{icon} {label}</button>)}{mode==="draft"&&<button disabled={busy} onClick={()=>submit("Outra versão")}>↻ Quero outra versão</button>}</div></div>
 <details><summary>Entenda a técnica <span>＋</span></summary><div className="tech">{[["Observação","Separar o fato da interpretação."],["Sentimento","Perceber o que isso despertou."],["Necessidade","Entender o que importa aqui."],["Pedido","Dizer o que você gostaria que acontecesse."]].map(([a,b])=><p key={a}><strong>{a}</strong>{b}</p>)}</div></details></section>}</section>
 <footer><p>Menos disputa. Mais conversa. <span>✳</span></p><small>Desenvolvimento: Larissa Maluf <a href="https://instagram.com/larissamaluf" target="_blank" rel="noreferrer">@larissamaluf</a></small></footer></main>
}
