"use client";
import { useEffect, useRef, useState } from "react";
type Answer = Record<string, string> & { variations?: string[] };
const examples = ["Meu pai falou que veganismo é frescura…", "Minha amiga fez uma piada que me incomodou…", "Meu namorado nunca ajuda nas tarefas de casa…", "Minha chefe falou comigo de um jeito que eu não gostei…"];
const situations = ["Mas e as plantas?", "Só um pedacinho não vai te matar.", "Na minha casa você come o que tiver.", "Você vai ficar anêmica.", "Eu respeito vegano, só não respeito quem impõe.", "Agora tudo tem que ser vegano?"];
export default function Home() {
 const [text,setText]=useState(""),[example,setExample]=useState(0),[answer,setAnswer]=useState<Answer|null>(null),[mode,setMode]=useState<"story"|"phrase"|"draft">("story"),[source,setSource]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[more,setMore]=useState(false),[draftOpen,setDraftOpen]=useState(false),[draft,setDraft]=useState(""),[listening,setListening]=useState(false);
 const recognition=useRef<any>(null);
 useEffect(()=>{const timer=setInterval(()=>setExample(v=>(v+1)%examples.length),3500);return()=>clearInterval(timer)},[]);
 async function ask(value:string,kind:"story"|"phrase"|"draft"="story",refine?:string){
  if(!value.trim()){setError("Conta um pouco do que aconteceu.");return}
  setBusy(true);setError("");setMode(kind);setSource(value);
  try{const response=await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:kind,text:value,refine,previous:refine?answer:null})});if(!response.ok)throw Error();setAnswer(await response.json());setTimeout(()=>document.getElementById("resultado")?.scrollIntoView({behavior:"smooth"}),50)}
  catch{setError("Não consegui responder agora. Tenta de novo?")}finally{setBusy(false)}
 }
 function voice(){const Speech=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Speech){setError("Seu navegador não oferece ditado por voz.");return}if(listening){recognition.current?.stop();return}const s=new Speech();recognition.current=s;s.lang="pt-BR";s.continuous=true;s.onresult=(e:any)=>{const said=Array.from(e.results).slice(e.resultIndex).map((r:any)=>r[0].transcript).join(" ");setText(v=>v+(v?" ":"")+said)};s.onend=()=>setListening(false);s.onerror=()=>setError("O ditado parou. Você pode continuar digitando.");s.start();setListening(true)}
 const variations=answer?.source==="safety"?[]:answer?.variations?.length?answer.variations:["Mais curta","Mais direta","Colocar um limite"];
 const explanation=answer?.explanation||answer?.approach||answer?.turn||"A frase aborda o ponto principal sem atacar a outra pessoa.";
 return <main className="shell"><header className="topbar"><a className="brand" href="#inicio"><span className="brand-mark">↝</span>conversa<span className="brand-dot">.</span></a><span className="top-note">menos ruído, mais conversa</span></header>
 <div className="ambient ambient-one" aria-hidden="true"/><div className="ambient ambient-two" aria-hidden="true"/>
 <section className="hero" id="inicio"><div className="hero-copy"><p className="eyebrow">✳ UM JEITO MELHOR DE DIZER</p><h1>Transformando<br/><em>conflito</em> em<br/>conversa<span className="period">.</span></h1><p className="subtitle">Tem uma conversa difícil pela frente?<br/>Me conta o que aconteceu.</p></div><div className="illustration" role="img" aria-label="Uma mensagem ganha clareza entre duas pessoas"><div className="person left"><span/></div><div className="speech first">A</div><div className="noise">≈<i>✳</i></div><div className="speech last">B</div><div className="person right"><span/></div><div className="path"/><small>o que eu disse <b>↝</b> o que chegou</small></div></section>
 <section className="main-flow"><div className="entry"><label htmlFor="situation">Pode contar do seu jeito…</label><div className="field"><textarea id="situation" value={text} maxLength={5000} onChange={e=>setText(e.target.value)} placeholder={examples[example]}/><button className={listening?"mic active":"mic"} aria-label={listening?"Parar ditado":"Falar em vez de digitar"} onClick={voice}>{listening?"■":"◉"}</button></div><button className="primary" disabled={busy} onClick={()=>ask(text)}>{busy?"Pensando numa boa resposta…":"Me ajuda a responder"} <span>↗</span></button>{error&&<p className="error" role="alert">{error}</p>}</div><div className="shortcuts"><p>Ou quer testar uma situação comum?</p><div className="chips">{situations.slice(0,more?situations.length:3).map((s,i)=><button key={s} disabled={busy} onClick={()=>ask(s,"phrase")}><span>{["🌱","🥩","⌂","♡","✳","↝"][i]}</span>{s}</button>)}</div><button className="more" onClick={()=>setMore(v=>!v)}>{more?"Ver menos":"Ver outras situações"} →</button></div></section>
 {answer&&<section className="result" id="resultado" aria-live="polite"><div className="result-inner"><p className="eyebrow">✳ UMA RESPOSTA POSSÍVEL</p>{answer.note&&<p className="notice">{answer.note}</p>}{mode==="draft"&&<div className="original"><span>Sua mensagem</span><p>“{source}”</p><b>↓</b></div>}<h2>{mode==="draft"?"Talvez funcione melhor assim:":"Eu responderia assim:"}</h2><div className="reply"><p>“{answer.reply}”</p><button aria-label="Copiar resposta" title="Copiar resposta" onClick={()=>navigator.clipboard.writeText(answer.reply)}>⧉</button></div>{variations.length>0&&<div className="adjust"><span>Quer ajustar?</span><div>{variations.slice(0,4).map(v=><button key={v} disabled={busy} onClick={()=>ask(source,mode,v)}>{v}</button>)}</div></div>}<details className="why"><summary>{mode==="draft"?"O que mudou?":"Por que essa resposta funciona?"} <span>＋</span></summary><p>{explanation}</p></details>{mode!=="draft"&&<div className="draft-link"><p>Já escreveu sua resposta?</p><button onClick={()=>setDraftOpen(v=>!v)}>Cole aqui e eu te ajudo a melhorar →</button></div>}{draftOpen&&mode!=="draft"&&<div className="draft-box"><label htmlFor="draft">Sua mensagem, do jeito que está</label><textarea id="draft" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Você sempre faz isso. É impossível conversar com você…"/><button className="primary" disabled={busy||!draft.trim()} onClick={()=>ask(draft,"draft")}>Melhorar minha mensagem <span>↗</span></button></div>}</div></section>}
 <footer><span>Uma conversa de cada vez. <b>✳</b></span><small>Desenvolvimento: Larissa Maluf <a href="https://instagram.com/larissamaluf" target="_blank" rel="noreferrer">@larissamaluf</a></small></footer></main>
}
